apiVersion: kafka.strimzi.io/v1alpha1
kind: ZookeeperBackup
metadata:
  name: my-cluster-cron
  labels:
    strimzi.io/cluster: my-cluster
spec:
  endpoint: my-cluster-zookeeper-client:2181
  storage:
    type: s3
  schedule:
    cron: '* * * * *'
  suspend: false
  retention:
    time: 15d
