apiVersion: kafka.strimzi.io/v1alpha1
kind: ZookeeperRestore
metadata:
  name: my-cluster-restore
  labels:
    strimzi.io/cluster: my-cluster
spec:
  endpoint: my-cluster-zookeeper-client:2181
  restore:
    type: s3
    full: true
  snapshot:
    id: 1555423331
