apiVersion: v1
kind: Template
metadata:
  name: strimzi-zookeeper-restore
  annotations:
    openshift.io/display-name: "Zookeeper Restore"
    description: >-
      This template creates a ZookeeperRestore. Used in conjunction with
      the Strimzi zookeeper operator, this will start the restore workflow of Zookeeper cluster.
      For more information about using this template see http://strimzi.io
    tags: "messaging"
    iconClass: "fa fa-hdd-o"
    template.openshift.io/documentation-url: "http://strimzi.io"
parameters:
  - name: CLUSTER_NAME
    displayName: Name of the Kafka cluster
    description: Specifies the name of the Kafka cluster in which the topic should be created.
    required: true
    value: my-cluster
  - name: STORAGE_TYPE
    displayName: Storage type to use for backup and restore
    description: Specifies the storage type to use, supported persistent-claim and s3.
    required: true
    value: persistent-claim
  - name: FULL_RESTORE
    displayName: Full restore procedure
    description: Triggers full or not restore procedure.
    required: true
    value: 'false'
  - name: SNAPSHOT_ID
    displayName: Snapshot ID
    description: Specified the snapshot id to restore in Zookeeper
    required: true
objects:
- apiVersion: kafka.strimzi.io/v1alpha1
  kind: ZookeeperRestore
  metadata:
    name: ${CLUSTER_NAME}-adhoc
    labels:
      strimzi.io/cluster: "${CLUSTER_NAME}"
  spec:
    endpoint: ${CLUSTER_NAME}-zookeeper-client:2181
    restore:
      type: ${STORAGE_TYPE}
      full: ${FULL_RESTORE}
    snapshot:
      id: ${SNAPSHOT_ID}