apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-cluster-burry-test
  labels:
    strimzi.io/cluster: my-cluster
    strimzi.io/name: my-cluster-burry-test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: my-cluster-burry-test
    spec:
      containers:
        - env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: my-cluster-zookeeper-client:2181
            - name: TLS_SIDECAR_LOG_LEVEL
              value: notice
            - name: KAFKA_CERTS_NAME
              value: zookeeper-operator
          image: openlabred/burry-stunnel:latest
          imagePullPolicy: Always
          name: tls-sidecar
          volumeMounts:
            - mountPath: /etc/tls-sidecar/burry/
              name: burry
            - mountPath: /etc/tls-sidecar/cluster-ca-certs/
              name: cluster-ca
        - name: burry
          image: openlabred/burry:latest
          command:
            - /usr/bin/tail
          args:
            - '-f'
            - '/dev/null'
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 1000m
              memory: 256Mi
            requests:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - mountPath: /home/burry
              name: volume-burry
      volumes:
      - name: cluster-ca
        secret:
          secretName: my-cluster-cluster-ca-cert
      - name: burry
        secret:
          secretName: my-cluster-backup-certs
      - name: volume-burry
        persistentVolumeClaim:
          claimName: my-cluster-backup-storage
  strategy:
    type: RollingUpdate