apiVersion: v1
kind: Template
metadata:
  name: strimzi-zookeeper-backup-pvc-cron
  annotations:
    openshift.io/display-name: "Zookeeper Backup Persistent Volume Claim - Cron"
    description: >-
      This template creates a ZookeeperBackup with Cron schedule and it persists in a persistent volume claim. Used in conjunction with
      the Strimzi zookeeper operator, this will start the backup workflow of Zookeeper cluster.
      For more information about using this template see http://strimzi.io
    tags: "messaging,datastore"
    iconClass: "fa fa-hdd-o"
    template.openshift.io/documentation-url: "http://strimzi.io"
parameters:
  - name: CLUSTER_NAME
    displayName: Name of the Kafka cluster
    description: Specifies the name of the Kafka cluster in which the topic should be created.
    required: true
    value: my-cluster
  - name: BACKUP_VOLUME_CAPACITY
    displayName: Backup Volume Capacity
    description: Volume space available for backup and restore in case of persistent claim type storage.
    required: false
    value: 1Gi
  - name: CRON_EXPRESSION
    displayName: Cron Expression for the CronJob
    description: Specifies the cron expression to be use on the CronJob.
    required: true
    value: "* * * * *"
  - name: SUSPEND_CRONJOB
    displayName: Suspend CronJob
    description: Suspend CronJob.
    required: false
    value: "false"
objects:
- apiVersion: kafka.strimzi.io/v1alpha1
  kind: ZookeeperBackup
  metadata:
    name: ${CLUSTER_NAME}-cron
    labels:
      strimzi.io/cluster: "${CLUSTER_NAME}"
  spec:
    endpoint: ${CLUSTER_NAME}-zookeeper-client:2181
    storage:
      type: persistent-claim
      size: ${BACKUP_VOLUME_CAPACITY}
      deleteClaim: false
    schedule:
      cron: ${CRON_EXPRESSION}
    suspend: ${SUSPEND_CRONJOB}