apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: strimzi-zookeeper-operator
  labels:
    app: strimzi
rules:
- apiGroups:
  - "kafka.strimzi.io"
  resources:
  - zookeeperbackups
  - zookeeperrestores
  verbs:
  - get
  - list
  - watch
  - create
  - patch
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - secrets
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - create
  - patch
  - update
  - delete
- apiGroups:
    - "batch"
  resources:
    - "*"
  verbs:
    - get
    - list
    - create
    - patch
    - update
    - delete
- apiGroups:
    - "apps"
  resources:
    - statefulsets
  verbs:
    - get
    - list
    - create
    - patch
    - update
    - delete