apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: strimzi-zookeeper-operator
  labels:
    app: strimzi
rules:
- apiGroups:
  - "kafka.strimzi.io"
  resources:
  - zookeeperbackups
  - zookeeperrestores
  verbs:
  - get
  - list
  - watch
  - create
  - patch
  - update
  - delete
  - deletecollection
- apiGroups:
  - ""
  resources:
  - secrets
  - persistentvolumeclaims
  - pods
  - events
  - pods/exec
  - pods/log
  verbs:
  - get
  - list
  - create
  - patch
  - update
  - delete
  - watch
- apiGroups:
    - batch
    - extensions
  resources:
    - jobs
    - cronjobs
  verbs:
    - get
    - list
    - create
    - patch
    - update
    - delete
- apiGroups:
    - apps
  resources:
    - statefulsets
  verbs:
    - get
    - list
    - create
    - patch
    - update
    - delete
- apiGroups:
    - extensions
  resources:
    - networkpolicies
  verbs:
    - get
    - list
    - watch
    - create
    - delete
    - patch
    - update
- apiGroups:
    - networking.k8s.io
  resources:
    - networkpolicies
  verbs:
    - get
    - list
    - watch
    - create
    - delete
    - patch
    - update