apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: zookeeperrestores.kafka.strimzi.io
  labels:
    app: strimzi
spec:
  group: kafka.strimzi.io
  versions:
  - name: v1beta1
    served: true
    storage: true
  - name: v1alpha1
    served: true
    storage: false
  version: v1beta1
  scope: Namespaced
  names:
    kind: ZookeeperRestore
    listKind: ZookeeperRestoreList
    singular: zookeeperrestore
    plural: zookeeperrestores
    shortNames:
    - zkr
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          properties:
            endpoint:
              type: string
            restore:
              type: object
              properties:
                full:
                  type: string
                type:
                  type: string
            snapshot:
              type: object
              properties:
                id:
                  type: string
                path:
                  type: string
              required:
              - id
          required:
          - endpoint
          - restore
          - snapshot
