apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: strimzi-zookeeper-operator
  labels:
    app: strimzi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: strimzi-zookeeper-operator
    spec:
      serviceAccountName: strimzi-zookeeper-operator
      containers:
        - name: zookeeper-backup-operator
          image: openlabred/zookeeper-operator:0.12.0
          env:
            - name: STRIMZI_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: STRIMZI_ZOOKEEPER_OPERATOR_TYPE
              value: backup
            - name: STRIMZI_LABELS
              value: "strimzi.io/cluster=my-cluster"
            - name: STRIMZI_CA_CERT_NAME
              value: my-cluster-cluster-ca-cert
            - name: STRIMZI_CA_KEY_NAME
              value: my-cluster-cluster-ca
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: "120000"
            - name: STRIMZI_LOG_LEVEL
              value: INFO
            - name: STRIMZI_GC_LOG_ENABLED
              value: "false"
            - name: STRIMZI_CA_VALIDITY
              value: "365"
            - name: STRIMZI_CA_RENEWAL
              value: "30"
            - name: STRIMZI_IMAGE_PULL_POLICY
              value: Always
            - name: STRIMZI_DEFAULT_ZOOKEEPER_OPERATOR_BURRY_IMAGE
              value: openlabred/burry:0.12.0
            - name: STRIMZI_DEFAULT_ZOOKEEPER_OPERATOR_TLS_SIDECAR_BURRY_IMAGE
              value: openlabred/burry-stunnel:0.12.0
          livenessProbe:
            httpGet:
              path: /healthy
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            limits:
              memory: 256Mi
              cpu: 500m
            requests:
              memory: 256Mi
              cpu: 100m
        - name: zookeeper-restore-operator
          image: openlabred/zookeeper-operator:0.12.0
          env:
            - name: STRIMZI_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: STRIMZI_ZOOKEEPER_OPERATOR_TYPE
              value: restore
            - name: STRIMZI_LABELS
              value: "strimzi.io/cluster=my-cluster"
            - name: STRIMZI_CA_CERT_NAME
              value: my-cluster-cluster-ca-cert
            - name: STRIMZI_CA_KEY_NAME
              value: my-cluster-cluster-ca
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: "120000"
            - name: STRIMZI_LOG_LEVEL
              value: INFO
            - name: STRIMZI_GC_LOG_ENABLED
              value: "false"
            - name: STRIMZI_CA_VALIDITY
              value: "365"
            - name: STRIMZI_CA_RENEWAL
              value: "30"
            - name: STRIMZI_DEFAULT_ZOOKEEPER_OPERATOR_RESTORE_TIMEOUT
              value: "600000"
            - name: STRIMZI_IMAGE_PULL_POLICY
              value: Always
            - name: STRIMZI_DEFAULT_ZOOKEEPER_OPERATOR_BURRY_IMAGE
              value: openlabred/burry:latest
            - name: STRIMZI_DEFAULT_ZOOKEEPER_OPERATOR_TLS_SIDECAR_BURRY_IMAGE
              value: openlabred/burry-stunnel:latest
          livenessProbe:
            httpGet:
              path: /healthy
              port: 8082
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: 8082
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            limits:
              memory: 256Mi
              cpu: 500m
            requests:
              memory: 256Mi
              cpu: 100m
  strategy:
    type: Recreate
