apiVersion: kafka.strimzi.io/v1alpha1
kind: ZookeeperRestore
metadata:
  name: msch-restore-example
  labels:
    strimzi.io/cluster: msch
spec:
  endpoint: msch-zookeeper-client:2181
  restore:
    type: persistent-claim
  snapshot:
    id: 1550849355
    path: /var/lib/backup
