apiVersion: kafka.strimzi.io/v1alpha1
kind: ZookeeperRestore
metadata:
  name: my-cluster-restore-example
spec:
  endpoint: my-cluster-zookeeper-client:2181
  restore:
    type: persistent-claim
    delete: true
    path: /var/lib/backup
    snapshot:
      id: 1549361319
