apiVersion: kafka.strimzi.io/v1alpha1
kind: ZookeeperBackup
metadata:
  name: my-cluster-adhoc
  labels:
    strimzi.io/cluster: my-cluster
spec:
  endpoint: my-cluster-zookeeper-client:2181
  storage:
    type: s3
    credentials: my-cluster-s3-credentials
  schedule:
    adhoc: 'true'
  retention:
    time: 15d
  snapshot:
    path: /var/lib/backup
