apiVersion: kafka.strimzi.io/v1alpha1
kind: ZookeeperBackup
metadata:
  name: my-cluster-cron
  labels:
    strimzi.io/cluster: my-cluster
spec:
  endpoint: my-cluster-zookeeper-client:2181
  storage:
    type: persistent-claim
    size: 1Gi
    deleteClaim: false
  schedule:
    cron: '52 10 * * *'
  suspend: 'false'
  retention:
    time: 15d
  snapshot:
    path: /var/lib/backup
