apiVersion: kafka.strimzi.io/v1alpha1
kind: ZookeeperRestore
metadata:
  name: my-cluster-restore
  labels:
    strimzi.io/cluster: my-cluster
spec:
  endpoint: my-cluster-zookeeper-client:2181
  restore:
    type: persistent-claim
    full: 'false'
  snapshot:
    id: 1554107117
    path: /var/lib/backup
